const info_c64 = {
"1942.d64":"Joystick port 2"
,"Abbaye Des Morts.d64":"Joystick port 2"
,"Alien 3.d64":"Joystick port 2"
,"Arc of Yesod.d64":"Joystick port 2"
,"Archon 2.d64":"Joystick port 2"
,"Archon.d64":"Joystick port 1"
,"Arkanoid.d64":"Joystick port 1"
,"Armalyte.d64":"Joystick port 2"
,"Bagman.d64":"Joystick port 2"
,"Barbarian 2.d64":"Joystick port 2"
,"Barbarian.d64":"Joystick port 2"
,"Battle Ships.d64":"Joystick port 2"
,"Beach Head 2.d64":"Joystick port 2"
,"Beach Head.d64":"Joystick port 2"
,"Biggles.d64":"Joystick port 2"
,"Biplanes.prg":"Joystick port 2"
,"Blue Max.d64":"Joystick port 2"
,"Bomb Jack.d64":"Joystick port 2"
,"Boulder Dash 2.d64":"Joystick port 1"
,"Boulder Dash 3.d64":"Joystick port 1"
,"Boulder Dash Construction Kit.d64":"Joystick port 1"
,"Boulder Dash.d64":"Joystick port 1"
,"Bruce Lee 2.d64":"Joystick port 2"
,"Bruce Lee Return of Fury.d64":"Joystick port 2"
,"Bruce Lee.d64":"Joystick port 1"
,"Bubble Bobble.d64":"Joystick port 2"
,"Burger Time.d64":"Joystick port 2"
,"Burnin Rubber.d64":"Joystick port 2"
,"C64anabalt.d64":"Joystick port 2"
,"Cab Hustle.d64":"Joystick port 2"
,"California Games.d64":"Joystick port 2"
,"Cauldron.d64":"Joystick port 2"
,"Cliff Hanger.d64":"Joystick port 2"
,"Colossus Chess 4.d64":"Joystick port 2. Wait 20 seconds after RUN, shift+J for joystick"
,"Commando.d64":"Joystick port 2"
,"Defender.d64":"Joystick port 1"
,"Desert Fox.d64":"Joystick port 2"
,"Dig Dug Revival.d64":"Joystick port 2"
,"Dino Eggs.d64":"Joystick port 2"
,"Doc Cosmos.d64":"Joystick port 2"
,"Donkey Kong Junior.d64":"Joystick port 2"
,"Donkey Kong.d64":"Joystick port 1"
,"Drip.d64":"Joystick port 2"
,"Druid.prg":"Joystick port 1"
,"Elite.d64":"Joystick port 2"
,"Emlyn Hughes Soccer.d64":"Joystick port 2. Game > Edit Team > Change COMPUTER to your name > Fire button twice > Tick > Play match"
,"Empire Strikes Back.d64":"Joystick port 2"
,"Enforcer.d64":"Joystick port 2"
,"Fist 2.d64":"Joystick port 2"
,"Fix-it Felix Jr.prg":"Joystick port 2"
,"Football Manager.d64":"Keyboard"
,"Fort Apocalypse 2.prg":"Joystick port 2"
,"Galencia.d64":"Joystick port 2"
,"Get Em DX.prg":"Joystick port 2"
,"Ghostbusters.d64":"Joystick port 1"
,"Ghosts 'n Goblins.d64":"Joystick port 2"
,"Ghouls 'n' Ghosts.d64":"Joystick port 2"
,"Great Giana Sisters.d64":"Joystick port 2"
,"Green Beret.d64":"Joystick port 2"
,"Grid Pix.prg":"Joystick port 2"
,"Gumshoe.d64":"Joystick port 2"
,"Hard 'n' Heavy.d64":"Joystick port 2"
,"Heli Rescue.d64":"Joystick port 2"
,"Iceblox.d64":"Joystick port 2"
,"Impossible Mission 2.d64":"Joystick port 2"
,"Impossible Mission Revised.d64":"Joystick port 2"
,"Impossible Mission.d64":"Joystick port 2"
,"International Football.d64":"Joystick port 2"
,"International Karate Plus.d64":"Joystick port 2"
,"International Karate.d64":"Joystick port 2. Press F1 to start"
,"Invert.d64":"Joystick port 2"
,"Jumpman.d64":"Joystick port 2"
,"Karateka.d64":"Joystick port 2"
,"Kobo 64.prg":"Joystick port 2"
,"Lady Pac.d64":"Joystick port 2"
,"Last Ninja 2.s1.d64":"Joystick port 2"
,"Last Ninja 2.s2.d64":"Joystick port 2"
,"Last Ninja.s1.d64":"Joystick port 2"
,"Last Ninja.s2.d64":"Joystick port 2"
,"Lester.prg":"Joystick port 2"
,"Lock 'n' Chase.d64":"Joystick port 2"
,"Lode Runner.d64":"Joystick port 2"
,"Manic Miner.d64":"Joystick port 2"
,"Mayhem in Monsterland.d64":"Joystick port 2"
,"Mediterranian Air War.prg":"Joystick port 1"
,"Microprose Soccer.d64":"Joystick port 2"
,"Mike Mech.d64":"Joystick port 2"
,"Millie and Molly.d64":"Joystick port 2"
,"Missile Defence.prg":"Joystick port 2"
,"Moon Cresta.d64":"Joystick port 2"
,"Mr Do.d64":"Joystick port 1"
,"Nebulus.d64":"Joystick port 2"
,"Night Knight.prg":"Joystick port 2"
,"Old Tower.prg":"Joystick port 2"
,"Ooze.d64":"Joystick port 2"
,"Orbital Rescue.d64":"Joystick port 2"
,"Outrun.d64":"Joystick port 1"
,"Oyup.d64":"Joystick port 2"
,"Pacman Arcade.d64":"Joystick port 2"
,"Pac-Man.d64":"Joystick port 2"
,"Paperboy.d64":"Joystick port 2"
,"Paradroid.d64":"Joystick port 2"
,"Pengo.prg":"Joystick port 2"
,"Penguin Tower.d64":"Joystick port 2"
,"Pitstop 2.d64":"Joystick port 2"
,"Pooyan.d64":"Joystick port 1"
,"Popeye.d64":"Joystick port 1"
,"Qix.d64":"Joystick port 1"
,"Qix.t64":"Joystick port 1"
,"Raid on Bungeling Bay.d64":"Joystick port 2"
,"Raid Over Moscow.d64":"Joystick port 2"
,"Rally Speedway.d64":"Joystick port 1"
,"RallyX.d64":"Joystick port 2"
,"Rambo First Blood Part 2.d64":"Joystick port 2"
,"Rampage.prg":"Joystick port 1"
,"Random Pac.d64":"Joystick port 2"
,"Rick Dangerous.d64":"Joystick port 2"
,"Robin of the Wood.d64":"Joystick port 2"
,"Robot Jet Action.prg":"Joystick port 2"
,"Robots Rumble.prg":"Joystick port 2"
,"Rodland.d64":"Joystick port 2"
,"R-Type.d64":"Joystick port 2"
,"Serpentine.d64":"Joystick port 1"
,"Shallow Domains.prg":"Joystick port 2"
,"Shamus.d64":"Joystick port 1"
,"Showdown.d64":"Joystick port 2"
,"Snafu 64.d64":"Joystick port 2"
,"Solomon's Key.d64":"Joystick port 2"
,"Space Pilot.d64":"Joystick port 2"
,"Spy Hunter.d64":"Joystick port 1"
,"Spy vs Spy 2.d64":"Joystick port 2"
,"Spy vs Spy 3.d64":"Joystick port 2"
,"Spy vs Spy.d64":"Joystick port 2"
,"Sub Hunter.d64":"Joystick port 2"
,"Summer Games 2.s1.d64":"Joystick port 2"
,"Summer Games 2.s2.d64":"Joystick port 2"
,"Summer Games.d64":"Joystick port 2"
,"Super Mario Bros.d64":"Joystick port 2"
,"Super Pipeline 2.d64":"Joystick port 2"
,"Super Pipeline.d64":"Joystick port 1"
,"Tenebra Macabre.prg":"Joystick port 2"
,"Train Escape to Normandy.d64":"Joystick port 2"
,"Turrican.s1.d64":"Joystick port 2"
,"Turrican.s2.d64":"Joystick port 2"
,"Tutankham Returns.d64":"Joystick port 2"
,"Uridium.d64":"Joystick port 2"
,"Vampire Vengeance.d64":"Joystick port 2"
,"Vegetables Deluxe.d64":"Joystick port 2"
,"Veggies vs Undead.prg":"Joystick port 2"
,"Volfied.d64":"Joystick port 2"
,"Way of the Exploding Fist.d64":"Joystick port 2"
,"Who Dares Wins 2.d64":"Joystick port 2"
,"Who Dares Wins.d64":"Joystick port 2"
,"WinGames.d64":"Joystick port 2"
,"Wizard of Wor.d64":"Joystick port 2"
,"Wizard of Wor.petscii.prg":"Joystick port 2"
,"Wizball.d64":"Joystick port 2"
,"Wolfling.prg":"Joystick port 2"
,"Yie Ar Kung-Fu.d64":"Joystick port 2"
,"Zeta Wing.d64":"Joystick port 2"
,"Zuma.prg":"Joystick port 2"
}