const info_vic20 = {
"Adventure Land.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"AE.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Alien Blitz.prg":"Memory expansion Dip ALL OFF   load\"*\",8   run"
,"Amok.prg":"Memory expansion Dip ALL OFF   load\"*\",8   run"
,"Arcadia.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Astro Nell.prg":"Memory expansion Dip ALL OFF   load\"*\",8   run"
,"Astroblitz.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Atlantis.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Attack of the Mutant Camels.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Avenger.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Bandits.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Battlezone.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Black Hole.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Blitz.prg":"Memory expansion Dip ALL OFF   load\"*\",8   run"
,"Bolder Dan.d64":"Memory expansion Dip ALL OFF   load\"*\",8   run"
,"Buck Rogers.d64":"Memory expansion Dip ALL OFF   load\"*\",8   run"
,"Capture the Flag.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Cheese and Onion.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Choplifter.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Cosmic Cruncher.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Creepy Corridors.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Defender.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Demon Attack.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Donkey Kong.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Dragonfire.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Escape 2020.d64":"Memory expansion Dip ALL OFF   load\"*\",8,1   run"
,"Final Orbit.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Galaxian.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Get More Diamonds.prg":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Gridrunner.prg":"Memory expansion Dip ALL OFF   load\"*\",8   run"
,"Help Bodge.prg":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Hero.d64":"Memory expansion Dip ALL ON   load\"*\",8,1   run"
,"Jelly Monsters.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Jetpac.prg":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Lala Prologue.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Laser Zone.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Lode Runner.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Manic Miner.prg":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Metagalactic Llamas.prg":"Memory expansion Dip ALL OFF   load\"*\",8   run"
,"Mickey the Bricky.prg":"Memory expansion Dip ALL OFF   load\"*\",8   run"
,"Miner 2049er.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Mission Impossible.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Moon Patrol.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Moons of Jupiter.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   run"
,"Mosquito Infestation.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Mountain King.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Ms Pac-Man.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Nibbler.prg":"Memory expansion Dip 6,7,8 ON   load\"*\",8   run"
,"Omega Race.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Pac-Man.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Pentagorat.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Perils of Willy.prg":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Pharaoh's Curse.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Pirate Cove.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Polaris.prg":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Pool.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   run"
,"Pumpkid.prg":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Radar Rat Race.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Rigel Attack.prg":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Robotron.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Robots Rumble.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Rockman.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Rodman.prg":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Sargon 2 Chess.prg":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Satellite Patrol.d64":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Satellites and Meteorites.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Scorpion.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Seafox.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Serpentine.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Shamus.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Skramble.prg":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Skyblazer.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Spider City.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Spiders of Mars.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Squish'em.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Star Battle.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Star Defence.prg":"Memory expansion Dip ALL ON   load\"*\",8   run   F1 to start"
,"Super Amok.prg":"Memory expansion Dip ALL ON   load\"*\",8,1   sys64802"
,"Sword of Fargoal.prg":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Tenebra Macabre.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"TenTen.prg":"Memory expansion Dip ALL OFF   load\"*\",8   run"
,"Tetris Deluxe.prg":"Memory expansion Dip 6,7,8 ON   load\"*\",8   run"
,"The Count.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Traxx.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Tutankham.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Vic Doom.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Video Vermin.d64":"Memory expansion Dip ALL ON   load\"*\",8 run"
,"Voodoo Castle.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
,"Zombie Calavera.d64":"Memory expansion Dip ALL ON   load\"*\",8   run"
}